### ISSUE TITLE
Rules that match request domain

### ISSUE THREAD

**Issue by bgrainger** [Tratcher/HttpRouteConfigBicep#3]
This feature request may already be coming as part of "Support for custom domains for the HTTProutingConfig", in which case I can wait for that to be released.

But just for clarity, I'd like to know how this scenario will/should be handled:

* We have a CAE with four apps, two of which have custom domains:
  * app1.example.com
  * app2.example.com
  * app3-v1.random-random.region.azurecontainerapps.io
  * app3-v2.random-random.region.azurecontainerapps.io
* The third and fourth apps are currently hosted at app3.example.com/v1 and app3.example.com/v2, being handled by an external load balancer that is receiving the traffic for app3.example.com
* I want to send traffic for app3.example.com to the CAE and have it route traffic to the third and fourth apps based on the request path (and remove the external load balancer).

If I create a `httpRouteConfig`, do I need to list out rules that match _all_ traffic coming to the CAE? That is, will I need explicit rules for app1.example.com and app2.example.com that match `/` and send all traffic to each respective CA? Or will requests to a custom domain just be handled "by default" if no other rule matches?

What is (or will be) the syntax for matching a domain for a request?

**Comment by Tratcher** [comment]
The httpRouteConfig would only need to include `app3.example.com` and its associated routing rules. app1 and app2 will continue to work as is.

The REST API docs for this are already posted and include samples: https://learn.microsoft.com/en-us/rest/api/resource-manager/containerapps/http-route-config/create-or-update?view=rest-resource-manager-containerapps-2024-10-02-preview&tabs=HTTP

We'll get these additional features deployed after the holidays.
